# Flags for GNU compiler
set(FMC_FFLAGS "-cpp -std=f2018 -ffree-line-length-none")
set(FMC_CFLAGS "-g")
if (CMAKE_Fortran_COMPILER_VERSION GREATER_EQUAL "10")
  message(STATUS "Set New Fortran basic flags")
  set(FMC_FFLAGS "${FMC_FFLAGS} -fallow-argument-mismatch")
  set(FMC_GNU10 TRUE)
else (CMAKE_Fortran_COMPILER_VERSION GREATER_EQUAL "10")
  set(FMC_GNU10 FALSE)
endif (CMAKE_Fortran_COMPILER_VERSION GREATER_EQUAL "10")
set(FMC_FFLAGS_RELEASE "-O3 -march=native")
set(FMC_FFLAGS_DEBUG   "-g3 -Og -ffpe-trap=invalid,zero -fcheck=all -fimplicit-none")
set(FMC_CFLAGS_RELEASE "-O3")
set(FMC_CFLAGS_DEBUG   "-g3 -Og -ffpe-trap=invalid,zero -fcheck=all -fimplicit-none")
